const header=document.querySelector('.site-header');
const progress=document.querySelector('.scroll-progress');
const menu=document.querySelector('.menu-toggle');
const nav=document.querySelector('.main-nav');
const heroImage=document.querySelector('.hero-image');
const update=()=>{const y=window.scrollY;header?.classList.toggle('scrolled',y>18);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?(y/max)*100:0}%`;if(heroImage&&innerWidth>820)heroImage.style.transform=`scale(${1.03+Math.min(y/9000,.05)}) translateY(${y*.045}px)`};
update();addEventListener('scroll',update,{passive:true});
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
